/** Home page text (the pillar page). Every figure is read from params-2026.json or computed by the engine. */
import type { FAQ, Helpers } from '../lib/page-types';
import { P, bendPoints } from '../lib/engine/params';
import { displayDate } from '../lib/format';
import { computePia, benefitAtAge, fraRetirement, projectCareer, workerReduction, drcIncrease } from '../lib/engine/ss';

const c = P.ssa_examples_2026.caseA;
const usd0 = (n: number) => `$${Math.round(n).toLocaleString('en-US')}`;

export const HOME = {
  title: 'Social Security Calculator 2026: PIA Step by Step, 62 to 70',
  description: `Social Security calculator 2026: your PIA from wage-indexed earnings, 2026 bend points ${usd0(P.series.bend_points['2026'][0])}/${usd0(P.series.bend_points['2026'][1])}, and your benefit at 62, full age or 70. Free, no account.`,
  h1: 'Social Security calculator 2026: see how your benefit is built',
  intro: 'Your birth date and your pay are enough to rebuild the primary insurance amount the way the SSA actuaries do, then to compare starting at 62, at full retirement age or at 70.',
  resume: `A worker who turns 62 in 2026 and has steady earnings gets a primary insurance amount (PIA) equal to 90% of the first ${usd0(P.series.bend_points['2026'][0])} of average indexed monthly earnings, 32% of the part up to ${usd0(P.series.bend_points['2026'][1])} and 15% of the rest, rounded down to the dime. Those earnings are the best 35 years of covered pay, each one multiplied by the national average wage index of 2024 (${P.series.awi['2024'].toLocaleString('en-US')}) divided by the index of its own year, capped at the taxable maximum (${usd0(P.taxable_max_2026)} in 2026) and averaged over 420 months. The SSA's own example for 2026, a worker born in 1964 with ${c.aime.toLocaleString('en-US')} dollars of AIME, comes out at a PIA of $${c.pia.toFixed(2)} and ${usd0(c.benefit62)} a month at 62, which is 70% of the PIA because full retirement age is 67. Starting at 70 instead pays 124% of the PIA for life, and every check rises with the cost-of-living adjustment, ${P.cola_2026.pct}% for 2026.`,
  faqs: [
    { q: 'Is this the same number as my SSA statement?', a: `It uses the same formula, and on the SSA's published 2026 examples it lands on the same AIME and PIA to the dime. Your statement can differ for two reasons: it reads your real earnings record instead of a career rebuilt from one salary, and for people under 60 it projects your current pay forward. Paste your record into the earnings-record calculator to remove the first difference.` } as FAQ,
    { q: 'Why does the calculator ask for my day of birth?', a: 'Because the SSA considers you reach an age the day before your birthday. Someone born on the 1st of a month is treated as born in the previous month, and someone born on January 1 belongs to the previous birth year, which can change both the full retirement age and the formula year. The day also sets your payment Wednesday.' },
    { q: 'What happens if I worked fewer than 35 years?', a: `The missing years count as zeros in the average. With 30 years of earnings, five of the 35 slots are empty and the AIME falls by about a seventh compared with 35 years at the same pay. Working one more year at any wage replaces a zero, so it raises the benefit, which the calculator shows when you change the age you stop working.` },
    { q: 'Do I need 40 credits to get any retirement benefit?', a: `Yes. You earn one credit for each ${usd0(P.credits.qc_amount)} of covered earnings in 2026, four at most per year, so ${usd0(P.credits.qc_amount * 4)} of pay earns the year's maximum. Forty credits, usually ten years of work, make you fully insured. Credits only open the right: the amount comes from your average indexed earnings, not from the number of credits.` },
    { q: 'Does the result include the 2026 cost-of-living increase?', a: `For anyone who turned 62 in 2025 or earlier, yes: the PIA is raised by every COLA from the year you turned 62 through the ${P.cola_2026.pct}% increase effective December 2025. If you turn 62 in 2026 or later, no COLA applies yet, and results are shown in today's dollars because future wage indexes are unknown.` },
    { q: 'Can I still change my mind after I start benefits?', a: `Within ${P.claiming.withdraw_within_months} months of your first month of entitlement you can withdraw your application once, repaying everything received, and the SSA treats you as if you had never filed (20 CFR 404.640). After full retirement age you can also ask to suspend payments and earn delayed retirement credits until 70.` },
    { q: 'How much is the maximum Social Security benefit in 2026?', a: `For someone who earned at least the taxable maximum every year since age 22, the SSA's 2026 examples give ${usd0(P.max_benefit_2026.age62)} a month when starting at 62, ${usd0(P.max_benefit_2026.age67)} at 67 and ${usd0(P.max_benefit_2026.age70)} at 70. Very few people reach those amounts: the average retired worker received ${usd0(P.stats_aug_2026.retired_worker_avg)} in August 2026.` },
    { q: 'Are teachers and public employees still cut by the WEP or GPO?', a: `No. The Social Security Fairness Act, signed on ${displayDate(P.ssfa.signed, 'en-US')} as Public Law ${P.ssfa.public_law}, repealed both the Windfall Elimination Provision and the Government Pension Offset for benefits payable after ${P.ssfa.applies_after}. A pension from work not covered by Social Security no longer reduces your own benefit or a spouse or survivor benefit.` },
  ],
  body: (h: Helpers) => {
    const ex = (y: number) => { const b = { y, m: 6, d: 15 }; const r = computePia(b, projectCareer(b, 60000, 22, 62)); return { r, fra: fraRetirement(y) }; };
    const rows = [1961, 1962, 1963, 1964].map((y) => { const { r } = ex(y); const bp = bendPoints(y + 62); return [String(y), String(y + 62), `${h.usd(bp[0])} / ${h.usd(bp[1])}`, h.usd(r.aime), h.usd(r.pia, 2)]; });
    const fra67 = fraRetirement(1960).total;
    return `
<h2>Why the year you turn 62 decides your formula</h2>
<p>Two neighbors born a year apart, with the same pay all their lives, do not get the same primary insurance amount. The law fixes your formula in the year you become eligible, which for retirement is the year you turn 62, and it indexes your earnings to the national average wage of the year you turned 60. After that, the PIA only moves with cost-of-living adjustments, while the bend points of the following years keep moving with wages. Most online estimators skip this and apply the current bend points to everyone. The table below shows what that hides, for a worker who earned the equivalent of ${h.usd(60000)} of today's pay from 22 to 62.</p>
${h.table(['Born in', 'Turns 62 in', 'Bend points of that year', 'AIME', 'PIA in 2026'], rows, 'Same career, four formula years: the PIA includes every COLA since 62', ['l', 'l', 'r', 'r', 'r'])}
<p>The person born in 1961 locked in the ${h.usd(bendPoints(2023)[0])} first bend point of 2023 and then received the COLAs of 2023, 2024 and 2025; the person born in 1964 gets the 2026 formula and no COLA yet. The differences are small in this example because wage growth and price growth were close over those years, but they are real money over twenty years of payments, and they are exactly what the SSA computes. The calculator above applies the formula of your own year, read from the ${h.src('ssaBendPoints', 'official table of bend points since 1979')}, and the COLAs listed in the ${h.src('ssaColaSeries', 'SSA series')}.</p>

<h2>The four steps the SSA follows</h2>
<h3>1. Index each year of earnings</h3>
<p>Every year of covered earnings before the year you turn 60 is multiplied by an indexing factor: the average wage index of your 60th year divided by the index of the year worked. In the SSA's 2026 example, ${h.usd(c.earnings_1986)} earned in 1986 becomes ${h.usd(c.indexed_1986)} (factor ${c.factor_1986}) because average wages were ${h.num(P.series.awi['2024'] / P.series.awi['1986'], 4)} times higher in 2024 than in 1986. Earnings from the year you turn 60 onward count at their face value. Pay above the year's ${h.a('taxable-maximum', 'taxable maximum')} is left out, which is why a high earner's benefit stops growing with salary.</p>
<h3>2. Keep the best 35 years</h3>
<p>The ${P.pia.computation_years} highest indexed years are added up and divided by 420 months. The result, rounded down to the dollar, is the ${h.a('aime', 'average indexed monthly earnings (AIME)')}. Years you did not work are not skipped: if you have fewer than 35 years, zeros fill the gap.</p>
<h3>3. Apply the PIA formula</h3>
<p>The AIME goes through three brackets separated by the ${h.a('bend-points', 'bend points')}: 90% of the first bracket, 32% of the second, 15% of the rest. The weighting is deliberate: a low earner gets back a much larger share of past pay than a high earner. An AIME of ${h.usd(3000)} gives a PIA of ${h.usd(Math.floor((0.9 * bendPoints(2026)[0] + 0.32 * (3000 - bendPoints(2026)[0])) * 10) / 10, 2)}, more than half of it; an AIME of ${h.usd(12000)} gives less than a third.</p>
<h3>4. Adjust for the age you start</h3>
<p>The PIA is what you get at ${h.a('full-retirement-age', 'full retirement age')}. Each month earlier removes 5/9 of 1% for the first 36 months and 5/12 of 1% beyond; each month later, up to 70, adds 2/3 of 1%. For anyone born in 1960 or later, with a full retirement age of 67, starting at 62 keeps ${h.pct(1 - workerReduction(fra67 - 62 * 12), 0)} of the PIA and waiting to 70 pays ${h.pct(1 + drcIncrease(70 * 12 - fra67), 0)}.</p>

<h2>62, full retirement age or 70: the break-even logic</h2>
<p>Starting early means more checks; starting late means bigger checks. The age at which the bigger checks catch up in total is the break-even age. For a full retirement age of 67, starting at 70 instead of 62 catches up around 80 and a half, in today's dollars; equal COLAs do not move that age because they raise both streams by the same percentage. The ${h.a('when-to-claim', 'claiming-age calculator')} runs the comparison for every start age with your own PIA. Two things weigh more than the break-even for many households: a married higher earner's delay raises the ${h.a('survivor-calculator', 'survivor benefit')} for the spouse who outlives, and working before full retirement age triggers the ${h.a('earnings-test', 'earnings test')}.</p>

<h2>What changed for 2026</h2>
<p>The ${h.src('frNotice2026', 'Federal Register notice of November 3, 2025')} set every figure this site uses: a ${P.cola_2026.pct}% COLA effective December 2025, a 2024 average wage index of ${h.num(P.series.awi['2024'], 2)}, bend points of ${h.usd(bendPoints(2026)[0])} and ${h.usd(bendPoints(2026)[1])}, a taxable maximum of ${h.usd(P.taxable_max_2026)}, ${h.usd(P.credits.qc_amount)} per credit and earnings-test limits of ${h.usd(P.earnings_test.lower_annual)} and ${h.usd(P.earnings_test.higher_annual)}. Medicare's standard Part B premium, usually taken from the check, rose to ${h.usd(P.medicare.part_b_2026, 2)} a month (${h.src('cmsPartB', 'CMS')}). And since the ${h.a('ssfa', 'Social Security Fairness Act')}, a pension from non-covered public work no longer reduces Social Security.</p>

<h2>What this calculator does not do</h2>
<p>It does not read your SSA record: either it rebuilds a career from one salary, assuming your pay kept the same rank against the national average every year, or you paste your record into the ${h.a('benefits-calculator', 'earnings-record calculator')}. It does not model disability benefits, the special minimum benefit for long low-wage careers, railroad retirement or foreign totalization agreements. For people who turn 62 after 2026 it gives today's dollars, as the SSA's Quick Calculator does. The ${h.a('method', 'method page')} lists every rule applied and the official examples the engine reproduces.</p>`;
  },
};
